# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Somali spellchecker"
so = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Somali, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
so = "TRANSLATE: A spellchecker for Somali, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.so"

[windows]
system_product_code = "{2EB6BF04-2BB0-41C8-8AEE-98CE7A658932}_is1"
legacy_product_codes = [
    { value = "634D46D5-33D4-4FB3-B210-7858072A3FF1", kind = "nsis" },
    { value = "6F2E7221-75FA-4CF3-97E6-03926D7CBA8C", kind = "nsis" }
]

[package.speller]
name = "Somali"
version = "0.1.1"

[package.grammar]
name = "Somali"
version = "0.1.0"

[package.tts-textproc]
name = "Somali"
version = "0.1.0"

[package.hyphenator]
name = "Somali"
version = "0.1.0"
