template = "https://github.com/giellalt/template-lang-und"
rev_id = 268
template_sha = "444a55f5c0c0489e8f1dcde2639b74c44c24dffb"

[replacements]
__GLOTTOLOG_ID__ = "soma1255"
__REPO__ = "lang-som"
__UND2C__ = "so"
__UNDEFINED__ = "Somali"
__UND__ = "som"
