template = "https://github.com/giellalt/template-lang-und"
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "soma1255"
__REPO__ = "lang-som"
__UND2C__ = "so"
__UNDEFINED__ = "Somali"
__UND__ = "som"
